{{-- resources/views/home.blade.php --}}
@extends('layouts.app')
@section('title', 'Jauxsh')

@section('content')
<div class="container mx-auto flex flex-col items-start gap-6 mt-20">
    <!-- Hero Image -->
    <div class="relative w-full h-[500px] md:h-[600px] lg:h-[700px] overflow-hidden rounded-lg shadow-lg">
        <img id="heroImage" 
             src="{{ asset('images/hero/hero1.png') }}" 
             alt="Hero Image"
             class="w-full h-full object-cover object-center transition-opacity duration-500">
        
        <!-- Minimalist Controls Overlay (Bottom Left) -->
        <div class="absolute bottom-4 left-4 flex items-center gap-3">
            <!-- Dots Indicator -->
            <div class="flex gap-1.5" id="dotsContainer">
                <!-- Dots will be generated by JS -->
            </div>

            <!-- Divider -->
            <div class="w-px h-4 bg-white/30"></div>

            <!-- Navigation Arrows -->
            <button onclick="previousSlide()" 
                    class="hero-control-btn w-7 h-7 flex items-center justify-center text-white border border-white/40 rounded-full transition-all duration-300">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
                </svg>
            </button>
            <button onclick="nextSlide()" 
                    class="hero-control-btn w-7 h-7 flex items-center justify-center text-white border border-white/40 rounded-full transition-all duration-300">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                </svg>
            </button>

            <!-- Divider -->
            <div class="w-px h-4 bg-white/30"></div>

            <!-- Play/Pause -->
            <button onclick="toggleAutoplay()" 
                    id="playPauseBtn"
                    class="hero-control-btn w-7 h-7 flex items-center justify-center text-white border border-white/40 rounded-full transition-all duration-300">
                <svg id="pauseIcon" class="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M6 4h4v16H6V4zm8 0h4v16h-4V4z"/>
                </svg>
                <svg id="playIcon" class="w-3.5 h-3.5 hidden" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M8 5v14l11-7z"/>
                </svg>
            </button>
        </div>

        <!-- Shop Button (Bottom Right) -->
        <div class="absolute bottom-4 right-4">
            <a id="shopBtn" href="/shop/jackets" class="shop-cta-btn inline-block px-6 py-1.5 font-lora text-white border-2 border-white/50 rounded-full transition-all duration-300">
                Shop →
            </a>
        </div>
    </div>
   
    <!-- Hero Title -->
    <h1 id="heroTitle" class="font-oswald text-3xl md:text-4xl tracking-widest uppercase text-gray-900 transition-opacity duration-500">
        Fleece Friends
    </h1>
    
    <!-- Hero Description -->
    <p id="heroDescription" class="max-w-2xl text-gray-600 text-sm md:text-base leading-relaxed transition-opacity duration-500">
        Sweatshirts naturally require the perfect pair of sweatpants to achieve maximum comfort.
        Add any sweatshirt and sweatpants to your cart and <span class="font-semibold text-gray-900">save 10%</span>!
    </p>

    <div>
        <h1 class="font-oswald text-2xl md:text-2xl tracking-widest uppercase text-gray-900 transition-opacity duration-500">Handsome made Fleece</h1>
    </div>
    <!-- List of Best Selling Products-->

    <!-- HEREE-->

    
</div>
@endsection

@push('scripts')
<script>
    // Hero content data
    const heroData = [
        {
            image: "{{ asset('images/hero/hero1.png') }}",
            title: "Fleece Friends",
            description: "Sweatshirts naturally require the perfect pair of sweatpants to achieve maximum comfort. Add any sweatshirt and sweatpants to your cart and <span class='font-semibold text-gray-900'>save 10%</span>!",
            shopLink: "/shop/jackets",  // Link for this slide
            shopText: "Shop Jackets →"   // Button text for this slide
        },
        {
            image: "{{ asset('images/hero/hero2.png') }}",
            title: "Summer Collection",
            description: "Discover our latest summer styles with breathable fabrics and vibrant colors. Perfect for warm weather adventures. <span class='font-semibold text-gray-900'>Shop now</span>!",
            shopLink: "/shop/summer",
            shopText: "Shop Summer →"
        },
        {
            image: "{{ asset('images/hero/hero3.png') }}",
            title: "Winter Warmth",
            description: "Bundle up in style with our cozy winter collection. Premium materials meet modern design. <span class='font-semibold text-gray-900'>Save 15% on bundles</span>!",
            shopLink: "/shop/winter",
            shopText: "Shop Winter →"
        }
    ];

    let currentSlide = 0;
    let autoplayInterval = null;
    let isAutoplayActive = true;

    // Initialize dots
    function initializeDots() {
        const container = document.getElementById('dotsContainer');
        container.innerHTML = '';
        
        heroData.forEach((_, index) => {
            const dot = document.createElement('button');
            dot.onclick = () => goToSlide(index);
            dot.className = index === 0 
                ? 'bg-white w-6 h-1.5 rounded-full transition-all duration-300 hover:bg-white/70' 
                : 'bg-white/40 w-1.5 h-1.5 rounded-full transition-all duration-300 hover:bg-white/70';
            container.appendChild(dot);
        });
    }

    // Update dots
    function updateDots() {
        const dots = document.querySelectorAll('#dotsContainer button');
        dots.forEach((dot, index) => {
            if (index === currentSlide) {
                dot.className = 'bg-white w-6 h-1.5 rounded-full transition-all duration-300 hover:bg-white/70';
            } else {
                dot.className = 'bg-white/40 w-1.5 h-1.5 rounded-full transition-all duration-300 hover:bg-white/70';
            }
        });
    }

    // Update slide content with fade effect
    function updateSlide(index) {
        const image = document.getElementById('heroImage');
        const title = document.getElementById('heroTitle');
        const description = document.getElementById('heroDescription');
        const shopBtn = document.getElementById('shopBtn');

        // Fade out
        image.style.opacity = '0';
        title.style.opacity = '0';
        description.style.opacity = '0';
        shopBtn.style.opacity = '0';

        setTimeout(() => {
            // Update content
            image.src = heroData[index].image;
            title.textContent = heroData[index].title;
            description.innerHTML = heroData[index].description;
            shopBtn.href = heroData[index].shopLink;
            shopBtn.textContent = heroData[index].shopText;

            // Fade in
            image.style.opacity = '1';
            title.style.opacity = '1';
            description.style.opacity = '1';
            shopBtn.style.opacity = '1';

            currentSlide = index;
            updateDots();
        }, 300);
    }

    // Navigation functions
    function nextSlide() {
        const nextIndex = (currentSlide + 1) % heroData.length;
        updateSlide(nextIndex);
        resetAutoplay();
    }

    function previousSlide() {
        const prevIndex = (currentSlide - 1 + heroData.length) % heroData.length;
        updateSlide(prevIndex);
        resetAutoplay();
    }

    function goToSlide(index) {
        updateSlide(index);
        resetAutoplay();
    }

    // Autoplay functions
    function startAutoplay() {
        if (autoplayInterval) clearInterval(autoplayInterval);
        autoplayInterval = setInterval(() => {
            nextSlide();
        }, 3500); // Change slide every 5 seconds
        isAutoplayActive = true;
        updatePlayPauseIcon();
    }

    function stopAutoplay() {
        if (autoplayInterval) {
            clearInterval(autoplayInterval);
            autoplayInterval = null;
        }
        isAutoplayActive = false;
        updatePlayPauseIcon();
    }

    function toggleAutoplay() {
        if (isAutoplayActive) {
            stopAutoplay();
        } else {
            startAutoplay();
        }
    }

    function resetAutoplay() {
        if (isAutoplayActive) {
            startAutoplay();
        }
    }

    function updatePlayPauseIcon() {
        const pauseIcon = document.getElementById('pauseIcon');
        const playIcon = document.getElementById('playIcon');
        
        if (isAutoplayActive) {
            pauseIcon.classList.remove('hidden');
            playIcon.classList.add('hidden');
        } else {
            pauseIcon.classList.add('hidden');
            playIcon.classList.remove('hidden');
        }
    }

    // Initialize on page load
    document.addEventListener('DOMContentLoaded', () => {
        initializeDots();
        startAutoplay();

        // Pause on hover
        const heroContainer = document.querySelector('.container');
        heroContainer.addEventListener('mouseenter', () => {
            if (isAutoplayActive) stopAutoplay();
        });
        heroContainer.addEventListener('mouseleave', () => {
            if (!isAutoplayActive) startAutoplay();
        });
    });
</script>

<style>
    /* Hero control buttons hover effect */
    .hero-control-btn:hover {
        background-color: #1fac99;
        border-color: #1fac99;
    }

    /* Shop CTA button hover effect */
    .shop-cta-btn {
        position: relative;
        overflow: hidden;
        transition: opacity 0.3s ease, color 0.3s ease, border-color 0.3s ease;
    }

    .shop-cta-btn::before {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        width: 0;
        height: 2px;
        background-color: #1fac99;
        transition: width 0.3s ease;
    }

    .shop-cta-btn:hover {
        border-color: #1fac99;
        color: #1fac99;
    }

    .shop-cta-btn:hover::before {
        width: 100%;
    }
</style>
@endpush